rust-paging/Cargo.toml
rust-tdshim/Cargo.toml
test_lib/Cargo.toml

Latest version "0.14.7" of x86_64 fails to build due to error[E0658]:
panicking in constant functions is unstable.

Fix version of crate x86_64 to "0.14.6"

---

rust-paging/Cargo.toml
rust-td-payload/Cargo.toml

Latest version of bootloader depends on the version 0.14.7 of x86_64,
so lock the version for now.

Lock version of crate bootloader

---

rust-tdshim/ResetVector/Main.asm
rust-tdshim/src/mp.rs

This is a regression introduced by MP memory acceptance.
Value of register r9 is used to store the cpu index of CPU, and it could
be changed by function assigned by BSP, so save the value into stack
before calling the function.
Correct the cpu exiting count value checked by BSP, APs can jump to
.check_command directly rather than .do_wait_loop.

rust-tdshim: fix MP wakeup issue

---

rust-test-payload/src/lib.rs
rust-test-payload/src/main.rs
rust-test-payload/src/tdinfo.rs

In rust-test-payload there are multi test cases, such as Tdinfo, Acpi,
Event log, Multi-processor, etc. This commit refines the rust-test-payload
so that developer can focuse on the test case itself.
There are below major changes.
1. trait TestCase
TestCase defines 5 interfaces which should be implemented by the actual
test case.
- setup(&mut self)
- run(&mut self)
- teardown(&mut self)
- get_name(&mut self) -> String
- get_result(&mut self) -> TestResult
2. struct TestSuite
testsuite is the member of TestSuite which holds the test cases which
implementes the trait of TestCase.
3. enum TestResult
Done means the test case is finished. Error means there is something
wrong when the case run.
Note: External parse script takes the responsibility to determines if
the test case pass or fail. …

rust-test-payload: Refine the test-payload

---

rust-td-layout/Cargo.toml
rust-td-layout/src/lib.rs
rust-td-layout/src/mailbox.rs
rust-td-layout/src/metadata.rs
rust-td-tool/src/main.rs

Enhance rust-td-layout by
1) add methods to validate structures
2) using `repr(C)` to ensure data structure layout
3) add more tests

Enhance rust-td-layout

---

rust-tdshim/Cargo.toml

rust-tdshim and rust-td-tool both use rust-td-layout as dependency.
If feature "boot-kernel" is not enabled, the auto-generated code
build-time.rs changed by rust-tdshim will be reused when rebuilding the
rust-td-tool.
Add this feature in rust-tdshim to fix this bug. It will be necessary to
enable this feature to boot kernel.

rust-tdshim: add feature "boot-kernel" pass down to rust-td-layout

---

devtools/dev_container/Dockerfile
devtools/dev_container/cargo_config

Add Dockerfile to build a container image for td-shim development
environment.

dev-container: add Dockerfile to build a dev container

---

doc/tdshim_spec.md

Fix typo Data -> Date
Bump version to 0.5.1 and date to February 2022.
Signed-off-by: Christophe de Dinechin <christophe@dinechin.org>

doc: Fix typo and bump version + date

---

doc/tdshim_spec.md

The HOB acronym is not particularly widespread, better to define it on first use
in the document.

doc: Define TD_HOB on first use

---

doc/tdshim_spec.md

Since we have no table of contents, make sure readers know there is a rather
extensive reference at the end of the document.

docs: Indicate that there is a reference early on in the document.

---

doc/tdshim_spec.md

Put hyperlinks to the reference sections where there is a reference to a
document that is listed there. Also split out various specific sections
describing ACPI tables.

docs: Put hyperlinks to reference section

---

Makefile
tdx-tdcall/Cargo.toml
tdx-tdcall/src/tdreport.rs
tdx-tdcall/src/tdx.rs

Refine the tdx-tdcall crate by:
1) use repr(C) to ensure correct data layout
2) impl as_bytes() for data structs
3) introduce TdxReportBuf to improve readability
4) move constant definition to a central place

tdx-tdcall: minor syntax improvements

---

.github/workflows/main.yml
rust-tdshim/Cargo.toml
rust-tdshim/src/ipl.rs
rust-tdshim/src/main.rs
rust-tdshim/src/tcg.rs
rust-tdshim/src/td/dummy.rs
rust-tdshim/src/td/mod.rs
rust-tdshim/src/td/tdx.rs
rust-tdshim/src/verifier.rs
td-layout/src/metadata.rs
td-payload/Cargo.toml
td-payload/src/main.rs
td-shim-enroll-key/Cargo.toml
td-shim-enroll-key/src/lib.rs
td-shim-enroll-key/src/main.rs
td-shim-ld/Cargo.toml
td-shim-ld/src/lib.rs
td-shim-ld/src/main.rs
td-shim-sign-payload/Cargo.toml
td-shim-sign-payload/src/lib.rs
td-shim-sign-payload/src/main.rs

The second part of td-shim refactor:
1) share common code among td-shim-ld. td-shim-enroll-key, td-shim-sign-payload and rust-tdshim/verifier.
2) refine tcg/verifier.
3) add feature "tdx" to rust-tdshim.

The second part of td-shim refactor

---

.github/workflows/devtools.yml
.github/workflows/format.yml
.github/workflows/library.yml
Cargo.toml
Makefile
devtools/Makefile
devtools/test-runner-client/Cargo.toml
devtools/test-runner-client/README.md
devtools/test-runner-client/src/lib.rs
devtools/test-runner-client/src/serial.rs
devtools/test-runner-server/Cargo.toml
devtools/test-runner-server/README.md
devtools/test-runner-server/src/main.rs
doc/test_in_no_std.md

Some td-shim components are compiled with `#[no_std]` and should be run
on physical/virtual machines. The normal rust test harness does not
support such cases, but it provides mechanisms to extend the stand test
harness. A pair of crates, test-runner-server and test-runner-client,
are implemented to run unit test cases for td-shim no_std components.
These components are used for development only, so hosted uner the
devtools directory.

test-runner: add crates to run tests for td-shim no_std components

---

doc/tdshim_spec.md

Add more kernel image type to the KernelInfo HOB, for vmlinux and auto-detection.

td-shim: add more kernel image type to KernelInfo HOB

---

Cargo.toml
Makefile
td-paging/Cargo.toml
td-paging/src/consts.rs
td-paging/src/frame.rs
td-paging/src/lib.rs
td-paging/src/page_table.rs

Add the td-paging to setup and manage page tables for td-shim.

td-paging: add crates to manage page table

---

.github/workflows/library.yml
Cargo.toml
Makefile
tdx-tdcall/Cargo.toml
tdx-tdcall/src/asm/mod.rs
tdx-tdcall/src/asm/tdcall.asm
tdx-tdcall/src/asm/tdcall_emu.asm
tdx-tdcall/src/asm/tdvmcall.asm
tdx-tdcall/src/asm/tdvmcall_emu.asm
tdx-tdcall/src/lib.rs
tdx-tdcall/src/tdreport.rs
tdx-tdcall/src/tdx.rs

The Intel TDX defines a group of TDCALLs, so the trusted domain may ask
for services from the underlying hardware/firmware. This crates defines
constants, structures and functions to access those services.

tdx-tdcall: introduce constants, structures and wrappers for tdcall services

---

Cargo.toml
Makefile
td-uefi-pi/Cargo.toml
td-uefi-pi/src/fv.rs
td-uefi-pi/src/hob.rs
td-uefi-pi/src/lib.rs
td-uefi-pi/src/pi/boot_mode.rs
td-uefi-pi/src/pi/fv.rs
td-uefi-pi/src/pi/hob.rs
td-uefi-pi/src/pi/mod.rs

The td-uefi-pi is a simple wrapper crate over r-efi, which provides:
1) constants and structures defined by the uefi specification
2) helper methods to handle uefi firmware volumes
3) helper methods to handle uefi HOB list.

[main] td-uefi-pi: a simple wrapper over r-efi for td-shim

---

devtools/test-runner-server/src/main.rs
td-shim-tools/src/bin/td-shim-enroll-key/main.rs
td-shim-tools/src/bin/td-shim-ld/main.rs
td-shim-tools/src/bin/td-shim-sign-payload/main.rs

Use command!() instead of deprecated app_from_crate!() to avoid clippy
warnings.

clap: use command!() instead of deprecated app_from_crate!()

---

Cargo.toml
Makefile
td-logger/Cargo.toml
td-logger/src/lib.rs
td-logger/src/logger.rs

A simple logger backend for td-shim, based on serial port.

[main] td-logger: a simple logger backend for td-shim

---

devtools/td-layout-config/config.json
devtools/td-layout-config/src/main.rs
td-layout/src/lib.rs
td-layout/src/memslice.rs
td-layout/src/runtime.rs
td-shim/src/bin/td-shim/asm/ap_loop.asm
td-shim/src/bin/td-shim/asm/mod.rs
td-shim/src/bin/td-shim/e820.rs
td-shim/src/bin/td-shim/main.rs
td-shim/src/bin/td-shim/td/tdx.rs
td-shim/src/bin/td-shim/td/tdx_mailbox.rs

This PR addresses these issues:
- Relocate the MAILBOX page to be continuous to the ACPI/event log regions #82
- Relocate the AP loop function to be continuous to the above area
- Use APIC ID instead of CPU index to identify AP 
APs are running in the loop waiting for BSP's instruction after they switch to long mode. At before, We assumed that CPU index get from TDCALL is equal to the APIC ID, but these two value may be different in some cases, such as configuring multiple sockets in QEMU.
One solution is to relocate APs' running loop into a new place where they use APIC ID to identify themselves. APs will use TDVMCALL to know their APIC ID and wait for the instructions from BSP to wakeup.
APs will run through two stages:
- At first stage, APs are waiting for BSP to assign works using CPU …

Relocate mailbox and AP function

---

Cargo.toml
Makefile
td-exception/Cargo.toml
td-exception/src/asm/idt.asm
td-exception/src/asm/mod.rs
td-exception/src/idt.rs
td-exception/src/interrupt.rs
td-exception/src/lib.rs

The td-exception crate manages x86 exceptions for td-shim, which
provides:
1) interrupt handlers
2) interrupt table manager

[main] td-exception: manage x86 exceptions for td-shim

---

.github/workflows/format.yml
.github/workflows/integration.yml
.github/workflows/library.yml
.github/workflows/main.yml
td-shim/Cargo.toml
td-shim/build.rs

Although the required tooling is documented in the README, it's too easy
to end up with a failed build due to missing tooling.
Add a new function to the build script to check for all dependencies and
fail with helpful messages on error.
Fixes: #110.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

td-shim: Check build tooling

---

.github/workflows/format.yml
.github/workflows/library.yml
.github/workflows/main.yml

Although the required tooling is documented in the README, it's too easy
to end up with a failed build due to missing tooling.
Add a new function to the build script to check for all dependencies and
fail with helpful messages on error.
Fixes: #110.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

td-shim: Make build script check for required commands

---

.github/workflows/main.yml
td-shim/build.rs

Fix: #134 
Add and modify CC and AR environment variables in .github/workflows/main.yml .
Modify the required_compiler variable value in build.rs to make it pass the check .

Modify environment variables so that CI can pass

---

.github/workflows/main.yml
Makefile
doc/test_with_td_payload.md
tests/test-td-payload/Cargo.toml
tests/test-td-payload/src/lib.rs
tests/test-td-payload/src/main.rs
tests/test-td-payload/src/test.json
tests/test-td-payload/src/testtdinfo.rs

Implement a simple test framework to run test cases with TDX dependency.
This PR depends on [PR 130](https://github.com/confidential-containers/td-shim/pull/130). It will use latest enroll tool to enroll the test json file in CFV. 

Refact test-td-payload in tests

---

td-layout/src/lib.rs
td-layout/src/memslice.rs
td-layout/src/metadata.rs
td-layout/src/runtime.rs

td-layout: add mailbox region to runtime layout.

[Move] td-layout: add mailbox region to runtime layout

---

tests/test-td-payload/Cargo.toml
tests/test-td-payload/src/main.rs
tests/test-td-payload/src/test.json
tests/test-td-payload/src/testtdve.rs

Use x86::io to write/read RTC and trigger #VE handler.

test-td-payload: Add #VE test case

---

tests/test-td-payload/Cargo.toml
tests/test-td-payload/src/main.rs
tests/test-td-payload/src/test.json
tests/test-td-payload/src/testacpi.rs

This is the initial version of ACPI test case. In this test case ACPI
tables will be checked if they exist in payload hob. In the next version
more check will be executed to the ACPI tables, such as the validness of
paticular fields.
Signed-off-by: Min Xu <min.m.xu@intel.com>

test-td-payload: Add ACPI test case

---

devtools/test-runner-client/Cargo.toml

Problem statement:
An error will be reported after the uart version is updated:
error: `ptr::mut_ptr::<impl *mut T>::add` is not yet stable as a const fn
--> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/uart_16550-0.2.17/src/mmio.rs:28:36
|
28 |             int_en: AtomicPtr::new(base_pointer.add(1)),
|                                    ^^^^^^^^^^^^^^^^^^^
|
= help: add `#![feature(const_ptr_offset)]` to the crate attributes to enable
error: `ptr::mut_ptr::<impl *mut T>::add` is not yet stable as a const fn
--> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/uart_16550-0.2.17/src/mmio.rs:29:39
|
29 |             fifo_ctrl: AtomicPtr::new(base_pointer.add(2)),
|                                       ^^^^^^^^^^^^^^^^^^^
|
= help: add …

Fixed uart_16550 version to 0.2.14

---

td-layout/src/lib.rs
td-paging/src/consts.rs
td-paging/src/frame.rs
td-paging/src/page_table.rs
td-shim/src/bin/td-shim/e820.rs
td-shim/src/bin/td-shim/main.rs
td-shim/src/bin/td-shim/memory.rs
td-shim/src/bin/td-shim/td/tdx_mailbox.rs

This pull request makes some refactoring on HOB and memory:
- Memory: make create_e820_table() and accept_memory_resources() as methods of struct Memory. 
Report all of the system memory to OS through E820 table.
- E820: enhance its implementation and add some interfaces to simplify E820 construction.
- Paging: Map all the memory reported by VMM.
- TD-Hob: parse TD-Hob into a struct instance to avoid parsing multiple times to get ACPI tables and 
Payload information etc.
And fix below issues:
- https://github.com/confidential-containers/td-shim/issues/131
- https://github.com/confidential-containers/td-shim/issues/121

Refactor memory implementation

---

tests/test-td-paging/src/lib.rs

test/test-td-paging: add feature default_alloc_error_handler to solver the error alloc_error_handler function required, but not found.
```
error: `#[alloc_error_handler]` function required, but not found.
Error: `#[alloc_error_handler]` function required, but not found.
note: Use `#![feature(default_alloc_error_handler)]` for a default error handler.
```

test/test-td-paging: add feature default_alloc_error_handler

---

.github/workflows/devtools.yml
.github/workflows/format.yml
.github/workflows/library.yml
.github/workflows/main.yml
Cargo.toml
td-payload/Cargo.toml
td-payload/src/main.rs

- Sync stagin branch CI
The rust version in format.yaml temporarily use nightly
```
error[E0554]: `#![feature]` may not be used on the stable release channel
--> /home/haowx/.cargo/registry/src/github.com-1ecc6299db9ec823/linked_list_allocator-0.9.1/src/lib.rs:1:41
|
1 | #![cfg_attr(feature = "const_mut_refs", feature(const_mut_refs))]
```
- Add members
Add members to let CI pass
-  td-payload
Update the dependent td-uefi-pi name in td-payload, which I forgot to update before

[Move] Update CI  and add members

---

.github/workflows/release.yaml
sh_script/build_final.sh

This series is a pre-req for being able to release the  TD-shim binaries as part of a tagged release.
This groundwork leverages the `build_final.sh` script, which currently builds the `final-pe.bin` and the `final-elf.bin` binaries, to also build a `final-pe-boot-kernel.bin` binary.
The new binary is basically the good and well known `final-pe.bin`, but built with the `boot-kernel` feature enabled, which is essential for using td-shim with Cloud Hypervisor.
Once this series is merged, we'll use this script as part of a GitHub action that will run once a release is tagged, generating then those binaries and attaching those as artefacts of the release.  The action will come on a different PR as it'll hit the `main` branch directly, while this series here targets the staging branch.
@jyao1, …

actions: Add an action for automatically doing releases and publishing the needed binaries

---

.github/workflows/release.yaml
sh_script/build_final.sh

This series is a pre-req for being able to release the TD-shim binaries as part of a tagged release.
This groundwork leverages the build_final.sh script, which currently builds the final-pe.bin and the final-elf.bin binaries, to also build a final-pe-boot-kernel.bin binary.
The new binary is basically the good and well known final-pe.bin, but built with the boot-kernel feature enabled, which is essential for using td-shim with Cloud Hypervisor.
Once this series is merged, we'll use this script as part of a GitHub action that will run once a release is tagged, generating then those binaries and attaching those as artefacts of the release. The action will come on a different PR as it'll hit the main branch directly, while this series here targets the staging branch.
@jyao1, please, take a …

[Move] actions: Add an action for automatically doing releases and publishing the needed binaries 

---

td-layout/Cargo.toml
td-layout/src/metadata.rs
td-shim-tools/Cargo.toml
td-shim-tools/src/bin/td-shim-checker/README.md
td-shim-tools/src/bin/td-shim-checker/main.rs
td-shim-tools/src/lib.rs
td-shim-tools/src/loader.rs
td-uefi-pi/src/pi/guid.rs

This PR corresponds to issue https://github.com/confidential-containers/td-shim/issues/81 which tries to resolve:
1. Parse td-shim binary to find out the TdxMetadata
2. Validate TdxMeatadata information and ensure it follows the td-shim spec
So we create one library and one tool.
1. Create a td-shim-loader library, that could be reused by the VMM. 
This library exports below function:
TdShimLoader::parse(filename: &String) -> Option<(TdxMetadataDescriptor, Vec<TdxMetadataSection>)>
2. Create a td-shim-checker tool (consuming td-shim-loader), to validate the format of the final binary.
cargo run -p td-shim-tools --bin td-shim-checker --no-default-features --features="loader" -- target/x86_64-unknown-uefi/release/final-pe.bi
In the meantime there are some other changes in other crates. …

Td shim checker

---

.github/workflows/release.yaml

Now that everything from the staging branch got merged into main,
there's no reason to keep the "staging" reference to the release
workflow.
Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

workflows,release: Rename action

---

devtools/test-runner-client/Cargo.toml
devtools/test-runner-server/Cargo.toml
td-exception/Cargo.toml
td-loader/Cargo.toml
td-shim/Cargo.toml

1. Correct Apache license name form "Apache 2.0" to "Apache-2.0"
2. Add license for package td-shim

Fix licenses info

---

doc/tdshim_spec.md

A TD-Shim may have zero, one or multiple TempMem. tdshim_spec wrongly
describe it.
Signed-off-by: Min Xu <min.m.xu@intel.com>

Fix tdshim_spec error

---

README.md

Add setting env steps in README.md to support
Elf format payload build.
Fix #259 

Add setting env steps for Elf format payload build in README.md

---

doc/tdshim_spec.md

For payload that does not follow the Linux Boot Protocol, it may have a
need to know the memory address where it is loaded.

doc: update td-shim spec to pass payload address

---

td-exception/src/interrupt.rs
tdx-tdcall/src/tdx.rs
tests/test-td-payload/config/test_config_1.json

Guest TD needs to retrieve the information when a #VE is injected by TDX
Module, otherwise TDX Module will inject a #DF next time it attempting to
inject a #VE.

Refactor #VE handler

---

td-payload/Cargo.toml
td-payload/src/json.rs

Fix: https://github.com/confidential-containers/td-shim/issues/250
A security vulnerability is detected inside crate chrono, and it is used
by td-payload as a demo, so we can just remove it.

td-payload: remove chrono

---

Cargo.toml
sh_script/build_final.sh
td-logger/Cargo.toml
td-reproducible-tool/Cargo.toml
td-reproducible-tool/readme.md
td-reproducible-tool/src/main.rs

fix #256
1. Introduce a reproducible tool, td-reproducible-tool, to help reproducible
2. Add strip = "symbols" to cargo.toml in root workspace to remove symbols
Signed-off-by: Longlong Yang <longlong.yang@intel.com>

Reproducible build: introduce a tool to help reproducible build

---

devtools/td-layout-config/src/main.rs
td-layout/src/runtime.rs
td-paging/src/consts.rs
td-paging/src/frame.rs
td-paging/src/lib.rs
td-paging/src/page_table.rs
td-shim/src/bin/td-shim/memory.rs
td-shim/src/bin/td-shim/payload_hob.rs
tests/test-td-paging/src/lib.rs

Caller may decide where to put the page table and how much memory should page table occupy. This makes the td-paging crate more reusable.        
- init() API will accept two arguments of base and size.
- FrameAlloc use vector to hold the bitmap. Heap is ready when setting up page table.

td-paging: make page table base and size as variable

---

td-exception/Cargo.toml
td-exception/src/idt.rs
td-exception/src/interrupt.rs
td-exception/src/lib.rs

Provide a public function to register handlers make it possible for users
out of crate to register its handler to specified index of global IDT.

td-exception: add an interface to register handler to IDT

---

td-shim-tools/src/bin/td-shim-strip-info/main.rs

fix #288 
Signed-off-by: Longlong Yang <longlong.yang@intel.com>

reproducible-tool: bug fix for the absence of binary write back.

---

td-loader/src/elf.rs
td-loader/src/pe.rs
td-payload/src/main.rs
td-shim/src/bin/td-shim/asm/switch_stack.asm
td-shim/src/bin/td-shim/ipl.rs
td-shim/src/bin/td-shim/main.rs
tests/test-td-payload/src/main.rs

As declared in td-shim spec that for ELF image, System-V ABI AMD64 calling
convention must be used. RDI must hold the payload HOB address, RSI must
hold the address where payload is loaded.

 td-shim: follow System V ABI when payload is ELF

---

tests/test-td-payload/config/test_config_1.json
tests/test-td-payload/config/test_config_2.json
tests/test-td-payload/config/test_config_3.json
tests/test-td-payload/config/test_config_4.json
tests/test-td-payload/config/test_config_5.json
tests/test-td-payload/src/testmemmap.rs

Address range from top of low memory (TOLM) to 4G is not for system memory
so we should exclude this range when calculating the system memory size.

tests: counting memory size ignores the reserved address range

---

td-shim/src/secure_boot.rs

Add check for readlen and header.length in secure_boot.rs

---

td-shim/src/bin/td-shim/asm/ap_loop.asm

Fix issue https://github.com/confidential-containers/td-shim/issues/321
According to ACPI specification section '5.2.12.19. Multiprocessor Wakeup
Structure', the application processor need clear the command to Noop(0) as
the acknowledgement that the command is received.

td-shim: clear 'command' when AP is waked up

---

devtools/td-layout-config/config.json
td-layout/src/runtime.rs
td-shim/ResetVector/CommonMacros.inc
td-shim/ResetVector/Main.asm
td-shim/src/bin/td-shim/main.rs
td-shim/src/bin/td-shim/memory.rs
td-shim/src/bin/td-shim/td/tdx.rs
td-shim/src/bin/td-shim/td/tdx_mailbox.rs

TD-Shim needs to setup page table for APs that maps all the system memory since the wakeup vector can be any memory address that is usable.
Here we use a same page table for BSP and AP. At the beginning, the page table of the AP only maps 0 to 4G. After BSP sets the page table, it wakes up all the APs and notifies them to reset CR3.
- Reduce the size of page table to 128KB by setting the frame size of runtime memory region to 4K and the rest to 1G. The default 128KB page table can map 12TB system memory.
- Cancel the NX protection for Linux Kernel since page table will be switched soon after transfer to Kernel, and setting the NX bit for mailbox or memory that is not reserved in E820 table will cause problem for AP wakeup.
- Page table for AP is set before relocating the AP waiting loop. …

td-shim: set up page table for APs that maps all system memory

---

td-loader/fuzz/fuzz_targets/fuzzlib.rs

Remove the third parameter in relocate_elf_with_per_program_header()

td-loader: Fix build issue of fuzzing test case

---

doc/tdshim_spec.md

To make the HOB_PAYLOAD_INFO_TABLE naturally aligned without padding, add
a u32 type reserved field in this struct.

doc: update td-shim spec to add a reserved field in payload info

---

td-loader/src/elf64.rs

td-loader: Use checked_add to avoid arithmetic overflow

---

td-uefi-pi/src/pi/fv.rs

td-uefi-pi: Use wrapping_add to avoid overflow

---

td-paging/src/page_table.rs

td-paging: Use checked_sub() to avoid overflow in page_table.rs

---

sh_script/integration_tdx.sh
td-logger/src/lib.rs
td-payload/Cargo.toml
td-payload/src/lib.rs
td-payload/src/main.rs
td-payload/src/serial.rs
td-shim/Cargo.toml
tests/test-td-payload/Cargo.toml
tests/test-td-payload/src/main.rs

Log message is disabled in td-shim release version and reserved in the
td-payload and test-td-payload.

Disable log message in release build

---

td-loader/fuzz/fuzz_targets/fuzzlib.rs
td-loader/src/elf.rs
td-loader/src/elf64.rs

Section header table is not loaded into memory, runtime initialization
program can use the `PT_DYNAMIC` segment to find the `.init_array` or
`.finit_array`.
Update the implementation of the `parse_init_array_section` function
and load all the program segment into memory.

td-loader: get .init_array with the PT_DYNAMIC segment

---

.github/workflows/release.yaml

While the release workflow looks for the 'final-pe-boot-kernel.bin' binary, the binary name should actually be 'final-boot-kernel.bin'
Fixes: #446
Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

github: Fix release workflow

---

cc-measurement/Cargo.toml
cc-measurement/src/log.rs
td-shim/Cargo.toml

For https://github.com/confidential-containers/td-shim/issues/294, use crate sha2 to calculate the hash digest.

cc-measurement: replace `ring` with `sha2`

---

td-shim/Cargo.toml
td-shim/src/acpi.rs

Any other crates that depend on `td-shim` will derive the feature of the `log` crate, so make it optional and enable it with `main`.

td-shim: disable crate `log` in td-shim library

---

devtools/td-benchmark/Cargo.toml
devtools/td-benchmark/src/benchmark.rs
devtools/td-benchmark/src/heap.rs
devtools/td-benchmark/src/lib.rs
devtools/td-benchmark/src/stack.rs

REF #456 
1.  Add heap stack profiling implementations - heap.rs and stack.rs
2.  Refactor `td-benchmark` library.
- make library structure more clearer.
- split lib.rs and make benchmark functions to a separate file benchmark.rs
- add a default feature `benchmark` for benchmark.rs. So heap.rs and stack.rs can be used without `td-layout`, `x86`, `scroll` dependencies.
Limitation: 
- this approach need change source code(less than 10 lines)
- limited by execution coverage. if program never reaches a particular function, the library collects no data.

Test runtime heap and stack usage.

---

td-shim/src/bin/td-shim/shim_info.rs

Fix: https://github.com/confidential-containers/td-shim/issues/458

td-shim: measure TD HOB using its real size

---

doc/test_code_coverage.md
td-payload/Cargo.toml
td-payload/src/bin/example/main.rs

REF: #472 
Rust compiler includes a code coverage implementation - enabled with `-C instrument-coverage`  to generate coverage data. 
But this can only be used in the `std` environment.
Currently td-shim and td-payload are both `no_std`. 
Provide a way to get code coverage `profraw` data in `no_std` environment. 
1. Get rid of `profiler-runtime`.
```
export RUSTFLAGS="-Cinstrument-coverage -Zno-profiler-runtime"
```
2. Provide a customer LLVM profiling runtime.
Minicov: https://github.com/Amanieu/minicov
```
minicov = { version="0.2", default-features = false}
```
3. Get coverage profiling data.
```
const COVERAGE_DATA_SIZE: usize = 0x300000;
let coverage_len = minicov::get_coverage_data_size();
let mut buffer: [u8; COVERAGE_DATA_SIZE] = [0; COVERAGE_DATA_SIZE];
assert!(actual_size <= …
```

RFC:  Get code coverage `profraw` data in `no_std` environment.

---

.gitignore

Prevent source files in the `bin` folders from being ignored
Fix: https://github.com/confidential-containers/td-shim/issues/477

remove `bin` from `.gitignore` file

---

td-shim-tools/Cargo.toml
td-shim-tools/src/bin/td-payload-reference-calculator/README.md
td-shim-tools/src/bin/td-payload-reference-calculator/main.rs

td-payload-reference-calculator helps to calculate the reference value of kernel (bzImage) and kernel parameter.
Close https://github.com/confidential-containers/td-shim/issues/487
Signed-off-by: Xynnn007 <xynnn@linux.alibaba.com>

td-shim-tools: add td-payload-reference-calculator

---

td-payload/src/bin/example/main.rs
td-payload/src/mm/dma.rs

Fix #494 ,DMA needs to be in scope when using pmemsave

Fix: no-std code coverage collection doesn't work

---

td-shim/src/bin/td-shim/memory.rs

Top of used low memory cannot be determined at TD-Shim build time because it is decided by metadata.
However, the memory area reserved by metadata must exist in separate resource entries, we don't need to explicitly check this value for a system memory entry.

td-shim: delete the check of `LOW_MEM_TOP`

---

tests/test-td-payload/Cargo.toml
tests/test-td-payload/src/main.rs

Note: Need to set DEFAULT_DMA_SIZE to 0x200000 before build
Signed-off-by: Liu Wei <wei3.liu@intel.com>

tests: Enable code coverage for test-td-payload

---

td-payload/src/arch/x86_64/apic.rs

Fix: https://github.com/confidential-containers/td-shim/issues/489
`asm_const` is not a stable feature, keep the `0x80B` and abstract the `eoi` as a macro

td-payload: abstract `eoi` as a macro

---

td-payload/src/mm/heap.rs
td-payload/src/mm/mod.rs

`cfg(not(test))` will not take effect when the crate is used as a dependency, use `target_os` instead.

td-payload: use `target_os` to replace `not(test)`

---

devtools/td-layout-config/config.json
devtools/td-layout-config/src/main.rs
td-exception/src/idt.rs
td-layout/src/lib.rs
td-layout/src/memslice.rs
td-layout/src/runtime.rs
td-shim/src/bin/td-shim/linux/boot.rs
td-shim/src/bin/td-shim/main.rs
td-shim/src/bin/td-shim/memory.rs

Fix: https://github.com/confidential-containers/td-shim/issues/476

td-shim: reuse mailbox memory for runtime IDT

---

td-exception/src/lib.rs

`asm_sym` is stable in the toolchain we use.

td-exception: remove attribute of enabling feature `asm_sym`

---

td-shim/build.rs

The `TD_HOB` args are never used by reset vector.

td-shim: remove using runtime layout in build script

---

td-exception/src/interrupt.rs
td-payload/src/arch/x86_64/apic.rs

Otherwise crates depend on these macros will need to explicitly claim the items used by these macros.

Use full path of macro and type dependencies in macros

---

td-shim/src/e820.rs

The 'From<&str>' implementaion can be used to get a E820Type from a string slice.
`PartialEq` and `Eq` are derived so that the type can be compared. `Debug` is derived for information dump, for example, by the `panic!`.

td-shim: add more implementations for `E820Type`

---

td-shim/src/bin/td-shim/linux/boot.rs
td-shim/src/bin/td-shim/main.rs
td-shim/src/bin/td-shim/td/tdx.rs
td-shim/src/bin/td-shim/td/tdx_mailbox.rs

The purpose of these changes is remove the using of `get_dynamic_mem_slice_mut` in helper functions.

td-shim: use mailbox slice for idt/mailbox relocation

---

td-shim/src/bin/td-shim/linux/boot.rs
td-shim/src/bin/td-shim/main.rs

The address of payload paramter may be different in different configurations so use slice instead.

td-shim: use `payload_parameter` slice for `boot_kernel()`

---

tdx-tdcall/src/tdx.rs

GHCI takes shared GPA as input for TDG.VP.VMCALL<GetQuote> leaf function.
To be compatible with different versions of qemu, add an option to choose whether to use shared GPA.

tdx-tdcall: use shared GPA for `GetQuote`

---

library/patches/ring.diff

This patch needs to be merged after #533 fix.
Fixed #532 
1. Remove x86_64-unknown-uefi support. Ref #533
2. Implement random function for ring by getrandom crate.
3. Fix ring compile warnings.

Update ring patch.

---

td-shim-tools/src/bin/td-payload-reference-calculator/main.rs

Add a `use` for `std::convert::TryFrom`.

td-shim-tools: fix build error in `td-payload-reference-calculator`

---

td-shim-tools/Cargo.toml
td-shim-tools/src/bin/td-payload-reference-calculator/main.rs
td-shim-tools/src/bin/td-shim-checker/main.rs
td-shim-tools/src/bin/td-shim-enroll/main.rs
td-shim-tools/src/bin/td-shim-ld/main.rs
td-shim-tools/src/bin/td-shim-sign-payload/main.rs
td-shim-tools/src/bin/td-shim-tee-info-hash/main.rs

Clap 4.0 enabled the feature showing help message for possible values which is very useful for us to add detailed description for the tools.
This will help the PR https://github.com/confidential-containers/td-shim/pull/530 to show the help message about `payload-type` options.
The new version deprecated `allow_invalid_utf8()` and `takes_value()`, we can use generic types and `ArgAction` instead.

td-shim-tools: upgrade `clap` version to 4.0+

---

.github/workflows/main.yml
README.md
doc/test_with_td_payload.md
sh_script/build_final.sh
td-shim-tools/src/bin/td-shim-ld/main.rs
td-shim-tools/src/linker.rs
td-shim-tools/src/metadata.rs

Fix: https://github.com/confidential-containers/td-shim/issues/523
td-shim-tool needs the type of payload to generate metadta for the image.
Previously, we used feature to distinguish types of payload, its disadvantage
is that we need to compile different executable files for different types.

td-shim-tools: use argument to determine the type of payload

---

sh_script/build_final.sh
td-layout/Cargo.toml
td-shim-tools/Cargo.toml
td-shim/Cargo.toml

Fix: https://github.com/confidential-containers/td-shim/issues/523
The use of `boot-kernel` features in `td-shim`, `td-layout` and `td-shim-tools` has been removed. We can remove these features now.

remove all the `boot-kernel` features

---

tests/test-td-payload/src/main.rs
tests/test-td-payload/src/testcetibt.rs
tests/test-td-payload/src/testcetshstk.rs
tests/test-td-payload/src/teststackguard.rs

Fix: https://github.com/confidential-containers/td-shim/issues/512
These cases are used to check whether the cet features and stack guard (guard page on the top of the stack) are correctly configured.
When the cet shstk feature is enabled and well configured, control flow exception will be triggered if the return address in the normal stack is not equal to the one in the shadow stack. This feature will be available only if the x86 shadow stack is enabled on the host and the feature is added to the TD configuration.
When the cet ibt feature is enabled and correctly configured, control flow exception will be triggered if the indirect branches are not landed on `endbr/endbr64` instruction. This feature is not fully supported by rust compiler.
Page fault exception will be triggered by stack …

tests: add cet shstk/ibt and stack guard cases

---

.cargo/config.toml
.github/workflows/main.yml
Cargo.toml
README.md
sh_script/build_final.sh
xtask/Cargo.toml
xtask/src/build.rs
xtask/src/main.rs

Fix: https://github.com/confidential-containers/td-shim/issues/528
Run `cargo image --help`
```
Usage: xtask image [OPTIONS]
Options:
--release
Build artifacts in release mode, with optimizations and without log messages
-t, --payload-type <PAYLOAD_TYPE>
Type of payload to be launched by td-shim
Possible values:
- linux:      Payload Binary is bzImage or vmlinux, follow Linux boot protocol
- executable: Payload Binary is a PE/COFF or ELF executable image as payload
-o, --output <OUTPUT>
Path of the output td-shim image file
--no-default-features
Disable the `default` features of td-shim crate, this flag will be set automatically when the payload type is executable
--features <FEATURES>
List of features to activate separated by comma
-m, --metadata <METADATA>
Path of customized metadata …
```

introduce xtask to build td-shim image

---

.github/workflows/main.yml
xtask/src/build.rs

Fix: https://github.com/confidential-containers/td-shim/issues/553
Strip is not necessary for debug build.

xtask: strip info only for the release build

---

tdx-tdcall/src/tdx.rs

Address of command and response buffer should be shared GPA according to GHCI.
Fix: https://github.com/confidential-containers/td-shim/issues/556

tdx-tdcall: use shared GPA for `TDG.VP.VMCALL<Service>`

---

tdx-tdcall/Cargo.toml
tdx-tdcall/src/tdx.rs

Fix: https://github.com/confidential-containers/td-shim/issues/558
According to GHCI, interrupt blocked flag should be cleared if `RFLAGS.IF=1` or the `tdcall` instruction immediately follows an `sti` instruction, otherwise this flag should be set

tdx-tdcall: use interrupt blocked flag for TDVMCALL HLT

---

td-shim-tools/src/bin/td-shim-tee-info-hash/main.rs

https://github.com/confidential-containers/td-shim/issues/568
Add an option to output the hash of tee info to stdout in string format

td-shim-tools/tee-info-hash: add option of string format output

---

Cargo.toml
cc-measurement/Cargo.toml
td-shim-tools/Cargo.toml
td-shim/Cargo.toml
tests/test-td-payload/Cargo.toml

Remove the `path` of patched ring in Cargo.toml to avoid the conflict when other crates use `td-shim` or `cc-measurement` and `ring` at the same time.
Fix: https://github.com/confidential-containers/td-shim/issues/569

use `[patch.crates-io]` for ring

---

sh_script/build_final.sh

Now no option named `pe` is in build_final.sh. This will lead to error when cutting release.
Fixes #572

sh_script: fix build_final.sh

---

devtools/td-benchmark/src/heap.rs

The reason is that the target platform is always 64 bit.

Change the type for heap_start to u64.

---

td-payload/src/arch/x86_64/apic.rs
tdx-tdcall/src/asm/mod.rs
tdx-tdcall/src/asm/tdvmcall.asm
tdx-tdcall/src/lib.rs
tdx-tdcall/src/tdx.rs

Fix: https://github.com/confidential-containers/td-shim/issues/561
Executing `hlt` instruction will cause a #VE to emulate the instruction. Safe halt operation `sti;hlt` which typically used for idle is not working in this case since `hlt` instruction must be the instruction next to `sti`. To use safe halt, `sti` must be executed just before `tdcall` instruction.

Add function to perform `sti;halt` operation

---

README.md

We do have lots of testing now.

remove the disclaimer for limitation.

---

td-shim/src/bin/td-shim/mp.rs

According to the latest ACPI spec, the mailbox version of MPWK should be 0.
Fix https://github.com/confidential-containers/td-shim/issues/596

td-shim: correct MPWK mailbox version

---

td-shim/src/bin/td-shim/main.rs

Align with `EDK2` implementation, to help OS to find the last event log entry.
Fix: https://github.com/confidential-containers/td-shim/issues/607

td-shim: init event log memory with `0xff`

---

README.md
devtools/dev_container/Dockerfile
sh_script/docker.sh

The reproducibility of td-shim is limited by the same system user and source code path, so we can use a Docker container to reproduce binaries.
Resolves: https://github.com/confidential-containers/td-shim/issues/604

add `Dockerfile` for reproducible build

---

td-shim/build.rs

The current script is checking if there is a change in ResetVector.asm file then re-run the cargo build script, but the filename is ResetVector.nasm instead.

td-shim: Fix a typo in build script

---

.github/workflows/devtools.yml
.github/workflows/integration.yml
.github/workflows/library.yml
.github/workflows/main.yml
.github/workflows/release.yaml

Remove the using of caches to avoid the `can't find crate` errors in CI.

.github: remove `Swatinem/rust-cache@v2`

---

tdx-tdcall/src/lib.rs
tdx-tdcall/src/tdx.rs

Fix: https://github.com/confidential-containers/td-shim/issues/498

td-payload: handle `retry` result of mapping GPA

---

Cargo.lock
cc-measurement/Cargo.toml
library/patches/ring.diff
sh_script/preparation.sh
td-shim-tools/Cargo.toml
td-shim-tools/src/bin/td-shim-sign-payload/main.rs
td-shim-tools/src/signer.rs
td-shim/Cargo.toml
td-shim/src/bin/td-shim/main.rs
tests/test-td-payload/Cargo.toml

- Upgrade `ring` git submodule.
- Update patch and patch script `preparation.h`.
- Update the use of `PublicKey` to follow the latest API.
- Update `Cargo.toml`s and `Cargo.lock`.
- Add `__assert_fail__` required by `ring` in `main.rs` .
Closes https://github.com/confidential-containers/td-shim/issues/613

upgrade `ring` to `0.17.5`

---

td-shim/src/bin/td-shim/main.rs
td-shim/src/bin/td-shim/shim_info.rs
td-shim/src/metadata.rs

Fixes https://github.com/confidential-containers/td-shim/issues/617

Measure payload only when EXTENDMR is not set

---

doc/tdshim_spec.md

TD_INFO is used to pass the information to the VMM on specific TD_SHIM information. E.g. the special service TD.

Add TD_info definition.

---

td-shim-tools/src/bin/td-shim-tee-info-hash/main.rs
td-shim-tools/src/bin/td-shim-tee-info-hash/readme.md
td-shim-tools/src/tee_info_hash.rs

add seperator extend support for tee info hash tool.

---

td-shim/src/bin/td-shim/shim_info.rs

skip making TD_INFO section a memory ResourceDescription.

---

README.md

This commit fixes the broken link that refers to the TD VF spec.

Fix broken TDSPEC link

---

Cargo.lock
cc-measurement/Cargo.toml
cc-measurement/src/lib.rs
td-payload/Cargo.toml
td-shim/Cargo.toml
td-shim/src/acpi.rs
td-shim/src/bin/td-shim/linux/kernel_param.rs
td-shim/src/bin/td-shim/mp.rs
td-shim/src/e820.rs
tests/test-td-payload/Cargo.toml

cargo-deny has reported security vulnerability against older version of zerocopy crate. Thus, we should upgrade to the latest version.
Advisory: https://rustsec.org/advisories/RUSTSEC-2023-0074

misc: Upgrade to latest version of zerocopy

---

cc-measurement/src/log.rs
td-exception/src/idt.rs
td-exception/src/interrupt.rs
td-layout/src/lib.rs
td-layout/src/runtime/exec.rs
td-layout/src/runtime/linux.rs
td-loader/src/elf.rs
td-loader/src/pe.rs
td-logger/src/lib.rs
td-paging/src/page_table.rs
td-payload/src/arch/x86_64/shared.rs
td-payload/src/mm/mod.rs
td-shim/src/acpi.rs
td-shim/src/bin/td-shim/memory.rs
td-shim/src/metadata.rs
td-uefi-pi/src/pi/fv.rs
td-uefi-pi/src/pi/hob.rs
tdx-tdcall/src/tdx.rs

Various components are throwing some trivial clippy warnings which are against the idiomatic rust pattterns.

misc: Fix reported clippy warnings

---

.github/workflows/integration-tdx.yml
sh_script/update_toolchain.sh

Resolve toolchain installation random issue in CI

---

td-shim/src/bin/td-shim/memory.rs

use safe func from_bits_retain instead.

unsafe func from_bits_unchecked was deprecated, 

---

.github/workflows/main.yml
td-shim-tools/Cargo.toml
td-shim-tools/src/bin/td-shim-checker/main.rs
td-shim-tools/src/lib.rs
td-shim-tools/src/loader.rs
td-shim-tools/src/read_file.rs

Fix: #654
Splited the file operation and std env from loader.rs. Moved the read file operation to read_file.rs.
Test the final.bin with td-shim-checker tool and it can get the right result.

Split file operation from loader.rs and change parse() API

---

td-payload/src/mm/shared.rs

The size needs to be aligned with 4KiB, panic if not.
Related issue: https://github.com/confidential-containers/td-shim/issues/662

td-payload: check the `size` for `init_shared_memory`

---

td-shim-tools/src/bin/td-payload-reference-calculator/README.md
td-shim-tools/src/bin/td-payload-reference-calculator/main.rs

Fix: #633 
Tested with local bzImage binary and the result is matched with the programe output mentioned in #633 .

Add support for caculating kernel eventlog digist when using OVMF+QEMU

---

td-payload/src/mm/shared.rs

Data in shared memory provided by VMM is untrusted so from a security perspective the data shall be consumed after being copied into private memory.
Private shadow for `SharedMemory` is provided to add a more easy and functional safe mechanism to use the untrusted data. It is 1:1 allocated for a shared memory request, and users can use the data with `copy_to_private_shadow` directly to get a private copy with additional memory allocation/free operations.

td-payload: add shadow pages for shared memory

---

devtools/td-layout-config/config_image.json

The bios image size alignment is checked by qemu. Remove the unused hole in the image

devtools: adjust image config to make the sum of region sizes align 0x10000

---

td-shim-tools/src/bin/td-payload-reference-calculator/main.rs

Fix: #676 
Tested with bzImage6.8 and get:
6ad357abcad6dd3c91cda809428937bb5915b48f71c961c603c78652c35452dc1286430fa59a54e47841a1ce1b9c5028
Match with:
Digest: 6ad357abcad6dd3c91cda809428937bb5915b48f71c961c603c78652c35452dc1286430fa59a54e47841a1ce1b9c5028

Improve the method for getting Region 1~3 base and size

---

.github/workflows/devtools.yml
.github/workflows/format.yml
.github/workflows/fuzz.yml
.github/workflows/integration-tdx.yml
.github/workflows/integration.yml
.github/workflows/library.yml
.github/workflows/main.yml
.github/workflows/release.yaml

`self-update` of rustup causes failure on Windows. As action-rs/toolchain is not maintained, switch to dtolnay/rust-toolchain.
Closes https://github.com/confidential-containers/td-shim/issues/698

ci: switch to dtolnay/rust-toolchain

---

td-layout/src/build_time.rs
td-layout/src/runtime/exec.rs
td-layout/src/runtime/linux.rs

`tera` changed its `filesizeformat` from `KB` to `kB`. This patch updates the source files with the new format.

td-layout: regenerate layout source files with `td-layout-config`

---

td-shim/src/bin/td-shim/e820.rs

Reducing the use of heap can improve the functional safety. For e820 implementation, use an fixed `MAX_E820_ENTRY` size array to replace the vector.
Relate issue: https://github.com/confidential-containers/td-shim/issues/685

td-shim: remove the use of `Vec` in `e820`

---

td-shim/src/bin/td-shim/td/tdx_mailbox.rs

Remove the use of heap can improve the functional safety. A piece of large enough static memory is allocated to hold the temparary stacks of APs which can support maximum 15 APs.
Related issue: https://github.com/confidential-containers/td-shim/issues/685

td-shim: use static memory for temp stacks of APs

---

td-shim/src/bin/td-shim/acpi.rs

Replace the vector with a fixed-array to record the table offsets of ACPI tables. The maximum number of ACPI tables is 128 according to Linux Kernel implementation.
Related issue: https://github.com/confidential-containers/td-shim/issues/685

td-shim: use fixed-size array for ACPI table installation

---

tdx-tdcall/Cargo.toml
tdx-tdcall/README.md

Prepare README.md and Cargo.toml for publishing tdx-tdcall crate

Upstream tdx-tdcall to crates.io

---

tdx-tdcall/src/tdx.rs

Use addr_of! macro instead of &

---

td-exception/src/interrupt.rs
td-payload/src/arch/x86_64/apic.rs
tdx-tdcall/src/tdx.rs

Ref: #708 
Replace the` tdvmcall_halt();` with `return Err(ret.into())`

Add Result return type for tdvmcall_wrmsr, tdvmcall_rdmsr

---

tdx-tdcall/src/tdx.rs

Fix: #708 
add vcpu_index field
```
pub struct TdInfo {
pub gpaw: u64,
pub attributes: u64,
pub max_vcpus: u32,
pub num_vcpus: u32,
pub vcpu_index: u32,
pub rsvd: [u64; 3],
}
```

Extend TdInfo struct to add vcpu_index field

---

devtools/td-layout-config/src/image.rs
devtools/td-layout-config/src/memory.rs
td-layout/src/runtime/mod.rs
td-payload/src/arch/mod.rs
td-shim-interface/src/td_uefi_pi/pi/guid.rs
td-shim/src/bin/td-shim/payload_hob.rs

Add copyright header

---

tdx-tdcall/CHANGELOG.md
tdx-tdcall/Cargo.toml

Update the tdx-tdcall cargo.toml
Version from 0.1.0 to 0.2.0
1. General clean up work
2. New APIs:
- Wrapper to tdcall_accept_page accept a memory range ( td_accept_memory that takes start address and len of address range to be accepted).
- Add tdcall_vm_read/write to access TD-scope meta field of a TD.
- Add tdcall_vp_read/write is to access vCPU-scope meta field of a TD.
- Add tdcall_vp_invept/invvpid to provide SEPT flushing support.
- Add tdcall_vp_enter support.
- Add tdcall to support memory attribute write.

Publish tdx-tdcall 0.2.0 for adding new functions to support TD partitioning

---

td-loader/fuzz/Cargo.toml
td-shim-interface/fuzz/Cargo.toml
td-shim/fuzz/Cargo.toml

Since the compiler of oss-fuzz is not the latest version, so it will meet build failure for crate "serde 1.0.204". So we use a fixed version serde "1.0.198" to fix the issue.

Fix oss-fuzz build failure issue

---

Cargo.lock
tdx-tdcall/Cargo.toml

External projects may not always choose to use the Rust nightly toolchain. Remove the nightly feature in the x86_64 crate to support the Rust stable toolchain. While we're at it, also bump up the x86_64 crate version to 0.15.1.

tdx-tdcall: remove nightly feature in the x86_64 crate

---

sh_script/integration_tdx.sh
sh_script/launch-rust-td.sh

Update the test script to support 8.0+ QEMU

Update script to support v8.0+ QEMU

---

tdx-tdcall/src/lib.rs
tdx-tdcall/src/tdx.rs

According to the ABI spec, TdCallError includes:
1) Flags, Class and Name (Bits 63:32)
2) Details L2 (Bits 31:0)
Fix the logic in fn from(val: u64) to correctly parse both parts of the function completion status. Include details L2 as part of the enum.

tdx-tdcall: fix TdCallError parsing

---

td-shim-tools/src/linker.rs

Update the checksum after setting the FV header.
Fixes: https://github.com/confidential-containers/td-shim/issues/729

td-shim-tools: fix the wrong IPL checksum

---

td-payload/src/arch/x86_64/init.rs
td-payload/src/lib.rs
td-payload/src/mm/shared.rs
tests/test-td-payload/src/main.rs

To keep the original API behavior unchanged. The extended API init the shared memory allocator with a private shadow start address. If the private shadow is not available, the method `copy_to_private_shadow` will return None.
As the `shadow_start` may be lower or higher than start of shared memory, the way of allocating private shadow is changed to use the offset of the allocated shared address to the start of shared allocator.
Closes https://github.com/confidential-containers/td-shim/issues/720

td-payload: add new shared memory init function with private shadow

---

td-shim/ResetVector/Ia32/Flat32ToFlat64.asm
td-shim/src/bin/td-shim/memory.rs

5-level paging is not necessary in td-shim, remove the related code and page table entry in reset vector.
As the level 5 entry is removed, update the size of `ResetVector` in image layout.
This PR should close https://github.com/confidential-containers/td-shim/issues/734 as GPAW is no longer needed.

ResetVector: remove 5-level paging

---

tdx-tdcall/src/lib.rs
tdx-tdcall/src/tdreport.rs

There's little reason to use a heap-allocated buffer for requesting TD reports putting it behind a global lock. Furthermore, the TDX module doesn't require the additional data to be inside the TD report buffer. Instead, put the buffer on the stack and directly pass a pointer to the additional data.
Note that with and without this patch, the memory passed to the TDX module must be identity-mapped.

tdx-tdcall: don't use heap allocated buffers for TD reports

---

td-payload/src/bin/example/main.rs
td-payload/src/lib.rs
td-payload/src/mm/heap.rs
td-shim/src/bin/td-shim/main.rs
tests/test-td-payload/src/main.rs

As the feature `default_alloc_error_handler` has been stablized, compiler can automatically generate a default OOM handler that panics if no `#[alloc_error_handler]` is provided.

remove `alloc_error_handler`

---

sh_script/preparation.sh

The following warning is being fixed:
warning: unused imports: `PKCS1`, `PSS`
--> ring/src/rsa/padding.rs:21:13
|
21 |     pkcs1::{PKCS1, RSA_PKCS1_SHA256, RSA_PKCS1_SHA384, RSA_PKCS1_SHA512},
|             ^^^^^
22 |     pss::{PSS, RSA_PSS_SHA256, RSA_PSS_SHA384, RSA_PSS_SHA512},
|           ^^^
|
= note: `#[warn(unused_imports)]` on by default
That warning was already fixed with this patch:
https://github.com/briansmith/ring/commit/c4742e0cae849f08ff410a817c5266af41670b3d
Once ring library version will be bumped up, this patch could be dropped.

Fix compilation warning in ring library

---

td-payload/src/mm/heap.rs

The following warnings are being fixed:
warning: unused import: `linked_list_allocator::LockedHeap`
--> deps/td-shim/td-payload/src/mm/heap.rs:6:5
|
6 | use linked_list_allocator::LockedHeap;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused import: `td_benchmark::Alloc`
--> deps/td-shim/td-payload/src/mm/heap.rs:8:5
|
8 | use td_benchmark::Alloc;
|     ^^^^^^^^^^^^^^^^^^^
warning: unnecessary `unsafe` block
--> deps/td-shim/td-payload/src/mm/heap.rs:30:5
|
30 |     unsafe {
|     ^^^^^^ unnecessary `unsafe` block
|
= note: `#[warn(unused_unsafe)]` on by default

Fix compilation warnings

---

td-exception/src/asm/handler.asm

The compiler may perform a circular right shift, resulting in incorrect assembly code for interrupt vectors greater than 64. Unconditionally push an error code of 0 for interrupt vectors greater than 31, as the CPU does not save an error code for these interrupts.

td-exception: fix interrupt handler condition

---

td-exception/src/interrupt.rs
td-payload/src/arch/x86_64/idt.rs

`InterruptCallback::new` shall be set as pub to make it possible for user of this crate to register callback via `register_interrupt_callback`.
Publicly use `td_exception::interrupt::*` in `td-payload` crate can help reduce redundant references to the `td-exception` crate.

td-exception: public `InterruptCallback::new`

---

library/patches/0001-NFC-Address-Clippy-unused-import-warning.patch
sh_script/preparation.sh

Following changes are a fixup for the https://github.com/confidential-containers/td-shim/pull/753 
It turned out that cherry-picking patches is not aligned with current CI workflow where fetching very limited number of revisions (branches, tags, sha, etc.).
Thus reverting previous commit and bringing new one based on keeping the patch locally in the repository

Fix compilations warnings in libraries

---

cc-measurement/Cargo.toml

Assuming BSD-2-Clause-Patent as parent directory

cc-measurement: Cargo.toml is missing license statement

---

td-payload/src/mm/mod.rs

Exposing the memory map allows the payload to use raw memory information.

td-payload: public the `MEMORY_MAP`

---

td-shim-interface/Cargo.toml
td-shim-interface/src/metadata.rs
td-shim/Cargo.toml

Some consumers of TD-Shim (such as TPA TD) might require td-shim to skip runtime metadata checks such as
signature check or entries attributes checks when the image is deliberately not compliant with TD-Shim specification.
This PR introduces new feature flag no-metadata-checks which allows user to skip those checks.

Introduce a new feature no-metadata-checks

---

Cargo.lock
td-logger/Cargo.toml
td-logger/src/lib.rs
td-payload/src/arch/x86_64/serial.rs
td-shim/Cargo.toml
tdx-tdcall/CHANGELOG.md
tdx-tdcall/Cargo.toml
tdx-tdcall/src/lib.rs
tdx-tdcall/src/tdx.rs

This PR adds support for newly defined tdg_dbg feature.
It introduces support for TDG.DEBUG ABI that's valid only with debug TDX Module, as defined in TDX Module 2.1 ABI specification.

Introduce a new feature tdg_dbg

---

td-logger/Cargo.toml
td-shim/Cargo.toml

Both td-shim and td-logger are used as libraries for different products. Declaring log-level as default feature prevents the consumers from overriding the log-level to higher value.
This change is to allow consumers to declare their own log-level.

td-shim,td-logger: remove default log level

---

tdx-tdcall/src/asm/mod.rs
tdx-tdcall/src/asm/tdvmcall_ex.asm
tdx-tdcall/src/lib.rs
tdx-tdcall/src/tdx.rs

Added functions to support new TDVMCALL_MIGTD leaf and subleafs.
Added new tdvmcall which passes RBX (and other registers) to VMM.

tdx-tdcall: support for new migtd ghci calls

---

Cargo.lock
td-shim-tools/Cargo.toml
td-shim-tools/src/bin/td-shim-ld/main.rs
td-shim-tools/src/linker.rs

Add an optional command-line parameter "--image-format" with possible values of "tdvf" and "igvm". The default is "tdvf". If "igvm" is specified, then the output image will be generated in the IGVM format. See https://crates.io/crates/igvm_defs.

td-shim-tools: add igvm support

---

td-shim-tools/Cargo.toml
td-shim-tools/src/enroller.rs
td-shim-tools/src/lib.rs
td-shim-tools/src/linker.rs
td-shim-tools/src/tee_info_hash.rs

Currently MRTD calculation is being done on binary format, this code ensures IGVM files are parsed for calculating MRTD hash. Also, currently Binary enrollment (CFV section) is being skipped for IGVM format, this commit supports it for IGVM files.

changes to support hashtool and enrollment on IGVM

---

td-payload/src/arch/x86_64/apic.rs

This commit adds OneShot APIC timer support. APIC divider (DCR) set to 1.

Support OneShot APIC timer for windows
