confidential-containers/td-shim

doc/secure_boot.md
=> RFC for td-shim secure boot support.

doc/tdshim_spec.md
Fix https://github.com/confidential-containers/td-shim/issues/8
=> Allow VMM to pass DSDT/SSDT to OS.

fuzzing/fuzz_elf_loader/src/main.rs
Signed-off-by: haowx <weiX.Hao@intel.com>
=> Optimize fuzz elf loader the is_elf function is true and it will run later.

fuzzing/fuzz_pe_loader/src/main.rs
Signed-off-by: haowx <weiX.Hao@intel.com>
=> Optimize fuzz pe loader, the is_pe function is true and it will run later.

fuzzing/fuzz_hob_parser/src/main.rs, rust-tdshim/src/ipl.rs, uefi-pi/src/hob_lib.rs
Signed-off-by: haowx <weiX.Hao@intel.com>
=> Follow tdx-logger pull request, hob_lib.rs add some checks.

doc/threat_model.md
=> Add side channel threat.

doc/tdshim_spec.md
Fix https://github.com/confidential-containers/td-shim/issues/9
=> Add clarification for payload type detection.

doc/cargo-deny.md
Signed-off-by: haowx <weiX.Hao@intel.com>
=> Add cargo-deny document.

Cargo.toml, rust-test-payload/.gitignore, rust-test-payload/Cargo.toml, rust-test-payload/src/main.rs, rust-test-payload/src/memslice.rs, rust-test-payload/target.json, rust-test-payload/x86_64-custom.json
This is a test payload for continuous validation. Currently, it contains cpu info check by TDCALL. All test cases development will be placed in this payload in the future.
Signed-off-by: Grace Zhou <grace.zhou@intel.com>
=> Add a test payload

rust-tdshim/ResetVector/Main.asm, rust-tdshim/src/mp.rs
Reverts confidential-containers/td-shim#26
=> Revert "rust-tdshim: fix MP wakeup issue"

.gitignore, Cargo.toml, devtools/Dockerfile, devtools/cargo_config
Add dockerfile to build docker image for dev environment.
=> Add dockerfile to build docker image for dev environment

Cargo.toml, rust-paging/Cargo.toml, rust-paging/src/consts.rs, rust-paging/src/frame.rs, rust-paging/src/lib.rs, rust-paging/src/paging.rs
Refactor the rust-paging crate by:
1) remove unused code from frame.rs
2) get rid of bitmap-allocator
3) refine doc
=> refactor rust-paging crate

doc/tdshim_spec.md
In order to make the document readable as text and not just as rendered on
github, wrap long lines to a reasonable size. This will also simplify later
diffs and reviews.
=> doc: Wrap long lines of markdown source

.gitignore
Add .gitignore file for the project.
=> dev-env: add .gitignore file

.github/workflows/library.yml, Cargo.toml, td-shim-ld/src/lib.rs, tdx-tdcall/.gitignore, tdx-tdcall/src/tdreport.rs
Minor improvements for tdx-tdcall and merge github action from main branch.
=> Minor improvements for tdx-tdcall

doc/tdshim_spec.md
=> Update document link to the latest one.

README.md
Let's update the README to reflect what's used as part of our github
actions.
Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>
=> README: Udpate build instructions

td-exception/src/interrupt.rs, td-shim/src/bin/td-shim/memory.rs, td-shim/src/bin/td-shim/td/dummy.rs, td-shim/src/bin/td-shim/td/tdx.rs
Fix #92 
Fix #93
Fix regression test failure.
=> Keep same as before refactoring.

td-shim-tools/Cargo.toml, td-shim/Cargo.toml
Fix a compilation failure caused by incorrect dependency.
Fixes: #95
=> td-shim: fix a dependency issue about td-layout

td-shim/src/bin/td-shim/main.rs, td-shim/src/bin/td-shim/mp.rs
Structures in MADT such as IOAPIC and Interrupt Source Override should be
provided by VMM since they may be different in different platforms. The
original MADT construction is simply based on the QEMU.
The only thing td-shim needs to do is to append the MP wakeup structure
to the end of the table and update the length and checksum, after it gets
the original one from VMM hob.
If there is no MADT table passed from VMM, td-shim constructs a default
one which contains APIC base and version, local APIC structure and MP
wakeup structure.
MADT reference: https://uefi.org/specs/ACPI/6.4/05_ACPI_Software_Programming_Model/ACPI_Software_Programming_Model.html#multiprocessor-wakeup-structure
=> td-shim: create MADT based on the table from VMM

doc/design.md, doc/static_analyzer.md
Fix: #111 
In case we find other static analyzer tool, we can add them here.
=> Rename rudra.md to static_analyzer.md.

td-exception/src/idt.rs, td-exception/src/interrupt.rs
Address feedback from https://github.com/confidential-containers/td-shim/pull/102
=> Clean up the td-exception.

td-layout/src/memslice.rs
Check some panic scenarios.
Fix #52
=> Add unit cases for td-layout/memslice.rs

td-layout/src/memslice.rs
Check functionality and some panic scenarios.
Code is same with the PR for staging. This PR is for master.
Fix #52
=> Add unit test case for td-layout/memslice.rs

Makefile, devtools/Makefile, devtools/dev_container/Dockerfile, sh_script/rudra.sh
Fix: #114 
I add environment in devtools/dev_container/dockerfile about fuzzing tools afl and libfuzzer and static analysis tool rudra.
I add docker call in devtools/makefile, start dockerfile run afl and libfuzzer and rudra.
Modify the changes in sh_script/rudra.sh.
=> Add tools to dockerfile and makefile

td-loader/src/pe.rs, td-shim-tools/src/enroller.rs, td-shim-tools/src/linker.rs, uefi-pi/src/fv.rs, uefi-pi/src/pi/fv.rs
- Solve the issues found by fuzz
- Add sanity check for firmware volume header
=> Add bounds and sanity checks in FV lib

td-exception/src/interrupt.rs
Introduce a `interrupt_common!()` macro to remove the duplication
between the `interrupt_error!()` and `interrupt_no_error!()` macros.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>
=> td-shim: Remove duplication in interrupt handler generation

.github/workflows/format.yml, .github/workflows/integration.yml, .github/workflows/library.yml, README.md
=> Update readme and CI files to consistent with the flags change in PR 138

td-uefi-pi/src/fv.rs, td-uefi-pi/src/pi/fv.rs, td-uefi-pi/src/pi/guid.rs, td-uefi-pi/src/pi/mod.rs
Migrate the staging branch uefi-pi to the main branch td-uefi-pi
=> [Move] td-uefi-pi is migrating main branch

td-exception/src/interrupt.rs, td-exception/src/lib.rs
=> [Move] td-exception: Clean up the td-exception.

td-paging/Cargo.toml
=> [Move] td-paging: Lock down to 0.44, otherwise it depends on inline asm

doc/secure_boot_guide.md
=> Fix build commands in doc/secure_boot_guide.md

doc/secure_boot.md, doc/secure_boot_guide.md, td-shim-tools/Cargo.toml, td-shim-tools/src/bin/td-shim-enroll/README.md, td-shim-tools/src/bin/td-shim-enroll/main.rs, td-shim-tools/src/bin/td-shim-ld/main.rs, td-shim-tools/src/bin/td-shim-sign-payload/README.md, td-shim-tools/src/bin/td-shim-sign-payload/main.rs, td-shim-tools/src/enroller.rs, td-shim-tools/src/lib.rs, td-shim-tools/src/linker.rs, td-shim-tools/src/public_key.rs, td-shim-tools/src/signer.rs
=> [Move] td-shim-tools: Migrate staging branch td-shim-tools to main branch

td-payload/Cargo.toml, td-payload/src/asm/cet_ss_test.asm, td-payload/src/asm/mod.rs, td-payload/src/asm/stack_guard_test.asm, td-payload/src/json.rs, td-payload/src/lib.rs, td-payload/src/main.rs, td-payload/src/mp.rs, td-payload/src/stack.rs, td-payload/x86_64-custom.json
=> [Move] td-payload: Migrate staging branch td-payload to main branch

td-shim/ResetVector/CommonMacros.inc, td-shim/ResetVector/DebugDisabled.asm, td-shim/ResetVector/Ia32/Flat32ToFlat64.asm, td-shim/ResetVector/Ia32/ReloadFlat32.asm, td-shim/ResetVector/Ia32/ResetVectorVtf0.asm, td-shim/ResetVector/Ia32/ValidateBfvBase.asm, td-shim/ResetVector/Main.asm, td-shim/ResetVector/Port80Debug.asm, td-shim/ResetVector/PostCodes.inc, td-shim/ResetVector/ResetVector.nasm, td-shim/ResetVector/SerialDebug.asm, td-shim/ResetVector/X64/PageTables.asm, td-shim/ResetVector/X64/TestHob.asm, td-shim/src/lib.rs, td-shim/src/reset_vector.rs
=> [Move] td-shim: Migration build ResetVector.bin

td-paging/src/frame.rs
Correct the miatake use of 'base' field of BMFrameAllocator, otherwise the
allocated frames will be started from a wrong value. The page table only
occupies 1M bytes memory at present, so the problem has not been exposed
yet.
In addition, a page must be reserved for level-4 table when we init the
frame allocator.
=> fix the regression on frame allocator for page table

doc/test_with_td_payload.md, tests/test-td-exception/Cargo.toml, tests/test-td-exception/src/lib.rs, tests/test-td-exception/x86_64-custom.json, tests/test-td-paging/Cargo.toml, tests/test-td-paging/src/lib.rs, tests/test-td-paging/x86_64-custom.json, tests/test-td-payload/Cargo.toml, tests/test-td-payload/src/lib.rs, tests/test-td-payload/src/main.rs, tests/test-td-payload/src/test.json, tests/test-td-payload/src/testiorw32.rs, tests/test-td-payload/src/testiorw8.rs, tests/test-td-payload/src/testtdinfo.rs, tests/test-td-payload/src/testtdreport.rs
tests: Run TDX hardware specific unit test cases inside a VM
tests: Run td-paging unit test cases inside a VM
tests: Run td-exception unit test cases inside a VM
=> [Move] tests: Migrate staging branch tests to main branch 

doc/design.md, doc/threat_model.md, td-shim/Cargo.toml, td-shim/src/acpi.rs, td-shim/src/bin/td-shim/acpi.rs, td-shim/src/bin/td-shim/asm/ap_loop.asm, td-shim/src/bin/td-shim/asm/mod.rs, td-shim/src/bin/td-shim/asm/msr64.asm, td-shim/src/bin/td-shim/asm/switch_stack.asm, td-shim/src/bin/td-shim/cet_ss.rs, td-shim/src/bin/td-shim/e820.rs, td-shim/src/bin/td-shim/heap.rs, td-shim/src/bin/td-shim/ipl.rs, td-shim/src/bin/td-shim/linux/boot.rs, td-shim/src/bin/td-shim/linux/kernel_param.rs, td-shim/src/bin/td-shim/linux/mod.rs, td-shim/src/bin/td-shim/main.rs, td-shim/src/bin/td-shim/memory.rs, td-shim/src/bin/td-shim/mp.rs, td-shim/src/bin/td-shim/stack_guard.rs, td-shim/src/bin/td-shim/tcg.rs, td-shim/src/bin/td-shim/td/dummy.rs, td-shim/src/bin/td-shim/td/mod.rs, td-shim/src/bin/td-shim/td/tdx.rs, td-shim/src/bin/td-shim/td/tdx_mailbox.rs, td-shim/src/bin/td-shim/verifier.rs, td-shim/src/event_log.rs, td-shim/src/fv.rs, td-shim/src/lib.rs, td-shim/src/secure_boot.rs
Signed-off-by: Xiaoyu Lu <xiaoyu1.lu@intel.com>
=> [Move] td-shim: Migrate staging branch td-shim to main branch

td-shim/build.rs
=> [Move] td-shim: Add build.rs

.cargo/config.toml
=> [Move] .cargo: Add cargo alias command

devtools/rustc-targets/x86_64-unknown-none.json
Fix:
- https://github.com/confidential-containers/td-shim/issues/75
=> td-payload: fix warning about different data layouts

devtools/Makefile, devtools/rustc-targets/x86_64-unknown-none.json
=> [Move] add tools and fix warning about different data layouts

fake/Cargo.toml, fake/src/lib.rs
=> fake: remove fake crate

td-paging/src/consts.rs, td-paging/src/frame.rs, td-paging/src/page_table.rs
=> [Move] td-paging: Migrate staging branch td-paging to main branch 

.gitignore, td-loader/fuzz/.gitignore
=> Merge .gitignore files and keep only one

license.md
Signed-off-by: haowei <weix.hao@intel.com>
=> [Move] license.md: Add license.md

doc/static_analyzer.md
=> rudra.md: nightly-2022-04-07 version cannot run rudra temporarily

.pre-commit-config.yaml
Signed-off-by: haowei <weix.hao@intel.com>
=> [Move] .pre-commit-config.yaml: Add .pre-commit-config.yaml

doc/secure_boot_guide.md
=> [Move] Fix build commands in doc/secure_boot_guide.md

Makefile
=> [Move] Makefile: Migrate staging branch Makefile to main branch 

doc/static_analyzer.md, sh_script/rudra.sh
=> [Move] Add static_analyzer tool

README.md
=> Main sync to staging: README.md

README.md
Signed-off-by: Christophe de Dinechin dinechin@redhat.com
=> [Move] update README.md

doc/static_analyzer.md
=> [Move] nightly-2022-04-07 version cannot run rudra temporarily

devtools/td-layout-config/config.json, devtools/td-layout-config/src/main.rs, td-layout/src/lib.rs, td-layout/src/runtime.rs, td-payload/Cargo.toml, td-payload/src/main.rs, td-shim/src/bin/td-shim/e820.rs, td-shim/src/bin/td-shim/main.rs, td-shim/src/bin/td-shim/memory.rs, td-shim/src/bin/td-shim/payload_hob.rs, td-shim/src/e820.rs, td-shim/src/lib.rs, tests/test-td-payload/src/main.rs, tests/test-td-payload/src/testacpi.rs
Fix below issues:
- https://github.com/confidential-containers/td-shim/issues/174
- https://github.com/confidential-containers/td-shim/issues/94
=> Handoff ACPI and E820 to executable(PE/ELF) payload through HOB

.github/workflows/integration-tdx.yml, sh_script/build_final.sh, sh_script/integration_tdx.sh, tests/test-td-payload/src/test.json, tests/test-td-payload/src/testmemmap.rs
.yml file is implemented by Arron.
Signed-off-by: Arron Wang <arron.wang@intel.com>
=> Add integration script and workflow for tdx server

.github/workflows/integration-tdx.yml, .github/workflows/main.yml, sh_script/build_final.sh, sh_script/integration_tdx.sh, tests/test-td-payload/config/README.md, tests/test-td-payload/config/test_config_1.json, tests/test-td-payload/config/test_config_2.json, tests/test-td-payload/config/test_config_3.json, tests/test-td-payload/config/test_config_4.json, tests/test-td-payload/config/test_config_5.json, tests/test-td-payload/src/main.rs
1. Add secure boot test case
2. Add more combination for integration test
3. Add meta data check in main.yml
=> Add more tdx integration test cases in CI

tests/test-td-payload/config/test_config_1.json, tests/test-td-payload/src/testacpi.rs
Add more checkpoints: signature revision oem_id
oem_table_id creator_id and checksum
=> tests: Add more checkpoints for testacpi

doc/tdshim_spec.md
=> Add clarification for AP page table.

td-shim/src/bin/td-shim/main.rs, td-shim/src/bin/td-shim/td_hob.rs, td-shim/src/lib.rs, td-uefi-pi/src/pi/hob.rs
Fix:
- https://github.com/confidential-containers/td-shim/issues/123
- https://github.com/confidential-containers/td-shim/issues/122
=> Add TD HOB sanity check and setup mitigations for Bounds Check Bypass

doc/tdshim_spec.md
Also defined in https://bugzilla.tianocore.org/show_bug.cgi?id=3873
=> Doc: Align CCEL to latest GHCI

doc/fuzzing.md, sh_script/fuzzing.sh, td-loader/fuzz/Cargo.toml, td-loader/fuzz/fuzz_targets/afl_elf.rs, td-loader/fuzz/fuzz_targets/afl_pe.rs, td-loader/fuzz/fuzz_targets/fuzzlib.rs, td-uefi-pi/fuzz/fuzz_targets/afl_cfv_parser.rs, td-uefi-pi/fuzz/fuzz_targets/afl_hob_parser.rs, td-uefi-pi/fuzz/fuzz_targets/afl_payload_parser.rs
- Cleanup the td-loader and td-uefi-pi fuzz
remove  redundant code
- Modify the fuzzing.sh
update afl run path where valid coverage report can be generated
- Update fuzzing.md
rust toolchain update, update related content
=> Fuzzing test update

td-loader/src/elf64.rs
Fix #263
td-lader/src/elf64.rs: Fix Relocs iteration may infinite loop
=> Fix Relocs iteration may infinite loop

.github/workflows/devtools.yml, .github/workflows/library.yml, Makefile, devtools/dev_container/Dockerfile
=> Update stable rust toolchain to 1.60.0

td-shim/src/bin/td-shim/main.rs, td-shim/src/bin/td-shim/tcg.rs, td-shim/src/bin/td-shim/td/tdx.rs, td-shim/src/event_log.rs, tests/test-td-payload/config/test_config_1.json, tests/test-td-payload/config/test_config_2.json, tests/test-td-payload/config/test_config_3.json, tests/test-td-payload/config/test_config_4.json, tests/test-td-payload/config/test_config_5.json, tests/test-td-payload/src/testtrustedboot.rs
Issue: https://github.com/confidential-containers/td-shim/issues/274
Update ACPI table signature and related event log definitions.
Update ACPI and trust boot test cases.
=> Update 'TDEL' to 'CCEL' according to spec

.github/workflows/main.yml, Makefile, td-layout/src/metadata.rs, td-shim-tools/src/enroller.rs, td-shim/src/e820.rs
1. Fix unit test case in td-shim/src/e820.rs
2. Fix unit test case in td-shim-tools/src/enroller.rs
3. Fix unit test case in td-layout/sec/metadata.rs
4. Add test in CI for SHIM_CRATES
Fix #281 
=> Fix unit test cases

doc/unit_test_coverage.md
Add steps of 2 new tools to collect test code coverage
for rust project.
=> Update readme of unit test coverage

doc/design.md
Refreshed some area.
Fix #284 
=> doc: Update design.md

td-shim/src/event_log.rs
Fix unit test case in event_log.rs
=> td-shim: Fix unit test case to pass CI

doc/tdshim_spec.md
=> Add trusted boot guideline.

td-payload/src/main.rs, td-uefi-pi/src/hob.rs, tests/test-td-payload/src/main.rs, tests/test-td-payload/src/testacpi.rs, tests/test-td-payload/src/testmemmap.rs, tests/test-td-payload/src/testtrustedboot.rs
1. Remove function get_hob_total_size
2. Update test cases in test td payload
3. Add more check points in check_hob_integrity
Fix #295 
Fix #298 
=> td-uefi-pi: Update hob.rs to fix security issues

td-shim-tools/src/bin/td-shim-strip-info/main.rs
fix #302
Signed-off-by: Longlong Yang <longlong.yang@intel.com>
=> reproducible-tool: clear timedatestamp and guid in PE image

td-shim/src/bin/td-shim/main.rs, td-shim/src/bin/td-shim/tcg.rs, td-shim/src/event_log.rs, tests/test-td-payload/src/testtrustedboot.rs
- Record the TCG_EfiSpecIDEvent as the first event.
- For TD HOB, extend it to RTMR[0] and record the event with event type EV_PLATFORM_CONFIG_FLAGS and event data being TD_SHIM_PLATFORM_CONFIG_INFO.
- For payload binary, extend it to RTMR[1] and record the event with event type EV_EFI_PLATFORM_FIRMWARE_BLOB2 and event data being UEFI_PLATFORM_FIRMWARE_BLOB2.
- For secure boot, extend the provisioned and matched trust anchor into RTMR[0] and payload SVN into RTMR[1] and record them with event type EV_PLATFORM_CONFIG_FLAGS and event data being TD_SHIM_PLATFORM_CONFIG_INFO.
- Before jumping to the TD payload, td-shim measures 0x0000_0000 and record the EV_SEPARATOR into the event log to mark the end of the td-shim events.
=> td-shim: follow the td-shim trust boot guideline

README.md, doc/test_with_td_payload.md
=> Fix some mistakes in readme

doc/tdshim_spec.md
Fix: #315
According to the ongoing patches of guest Kernel:
https://github.com/intel/tdx/tree/guest-unaccepted-memory, it does not
support the unaccepted type in E820 table and uses a bitmap to track the
unaccepted memory pages instead.
Since td-shim does not provide UEFI interface for OS to obtain the memory
map, it shall build a bitmap as it does in kernel EFI stub and
report the bitmap address to the Kernel through boot paramter.
The bitmap memory does not need to be explicitly reserved, because the
kernel will reserve it before initializing the memblock.
=> doc: update td-shim spec to support lazy-accept

doc/tdshim_spec.md
fix #316
Signed-off-by: Longlong Yang <longlong.yang@intel.com>
=> tdshim_spec: clarify MRTD calculation

td-shim/src/lib.rs
To align with https://github.com/confidential-containers/td-shim/pull/327
=> td-shim: add member `reserved` in `PayloadInfo`

.github/workflows/main.yml, sh_script/fuzzing.sh
To avoid build regression issue like #324 .
Fix #326 
=> Add build test for fuzzing test case in CI

tests/test-td-payload/src/testtrustedboot.rs
Cover RTMR[0~3] test
Fix #291 
=> tests: Enhance trusted boot test

td-shim-tools/Cargo.toml, td-shim-tools/src/bin/td-shim-tee-info-hash/main.rs, td-shim-tools/src/bin/td-shim-tee-info-hash/readme.md, td-shim-tools/src/bin/td-shim-tee-info-hash/sample_manifest.json, td-shim-tools/src/lib.rs, td-shim-tools/src/tee_info_hash.rs
Support MRTD calculation
Add sample manifest
Generate tee info hash binary
=> Add tee info hash tool

td-layout/src/runtime.rs, td-shim/src/bin/td-shim/linux/boot.rs
To boot RawVmlinux image.
Signed-off-by: Yonghao Wei <weiyonghao@linux.alibaba.com>
=> Boot rawvmlinux

td-loader/fuzz/fuzz_targets/fuzzlib.rs
Cover function parse_pre_init_array_section
=> td-loader: Fuzzing test case enhancement

td-layout/src/lib.rs, td-layout/src/mailbox.rs, td-layout/src/memslice.rs, td-layout/src/metadata.rs
Improve coverage from 55.35% to 97.18%
=> td-layout: Unit test enhancement

td-shim/fuzz/fuzz_targets/fuzzlib.rs, td-uefi-pi/fuzz/fuzz_targets/fuzzlib.rs
Update test case to have better ouput when running libfuzzer
=> Update fuzzing test case

td-uefi-pi/src/hob.rs, td-uefi-pi/src/pi/hob.rs
Improve the coverage from 76.16% to 89.19%
=> td-uefi-pi: Unit test enhancement

td-loader/src/elf.rs, td-loader/src/elf64.rs, td-loader/src/pe.rs
Improve coverage from 88.48% to 93.7%
=> td-loader: Unit test enhancement

td-uefi-pi/src/hob.rs
=> td-uefi-pi: Fix panic issue in line 52 of src/hob.rs

sh_script/integration_tdx.sh
=> Update CI test script to follow the latest CI environment

td-uefi-pi/src/pi/guid.rs, tdx-tdcall/src/lib.rs
There are 2 commits in this PR.
1. Add Clone,Copy traits for Guid
2. Add Debug trait for TdVmcallError
=> Tdvmcall guid change

td-logger/src/lib.rs
Improve the covergae from 78.26% to 94.74%
=> td-logger: Unit test enhancement

td-shim/src/acpi.rs, td-shim/src/e820.rs, td-shim/src/event_log.rs, td-shim/src/fv.rs, td-shim/src/lib.rs, td-shim/src/reset_vector.rs, td-shim/src/secure_boot.rs
Improve the coverage from 50.36% to 94.44%
=> td-shim: Unit test enchancement

tdx-tdcall/src/lib.rs, tdx-tdcall/src/tdx.rs
=> tdx-tdcall: Add check to avoid out of bounds

tdx-tdcall/src/tdreport.rs
=> tdx-tdcall: Fix out of bounds issue in tdreport.rs

td-uefi-pi/src/hob.rs
=> td-uefi-pi: Fix prusti warning

tdx-tdcall/src/tdx.rs
=> tdx-tdcall: Fix "Value might not fit into the target type" issue

doc/static_analyzer.md
=> Introduce how to do static analysis with Prusti

doc/static_analyzer.md
MIRAI is another static analysis tool.
This commit introduce how to use this tool.
Signed-off-by: Xiaoyu Lu <xiaoyu1.lu@intel.com>
=> Docs: Introduce MIRAI for static analysis

td-shim-tools/src/bin/td-shim-enroll/README.md, td-shim-tools/src/enroller.rs
=> td-shim-tools: perform basic check for public key

td-shim-tools/src/tee_info_hash.rs
Support search metadata offset with guid
=> Update tee_info_hash tool

td-uefi-pi/src/pi/hob.rs
=> td-uefi-pi: Replace to dump the length to avoid overflow

tdx-tdcall/src/tdreport.rs, tdx-tdcall/src/tdx.rs
=> tdx-tdcall: Fix potential overflow issues in tdx-tdcall

td-shim/build.rs
=> td-shim: Remove unnecessay parentheses in build.rs

doc/tdshim_spec.md
=> Add clarification for TD accepted memory.

.github/workflows/main.yml, sh_script/fuzzing.sh, td-loader/fuzz/Cargo.toml, td-shim/fuzz/Cargo.toml, td-uefi-pi/fuzz/Cargo.toml
=> Add fuzzing test in CI

td-layout/src/lib.rs
=> td-layout: correct the typo

td-shim/src/bin/td-shim/payload_hob.rs
=> td-shim: remove resource hobs for executable payload

td-shim-tools/src/enroller.rs, td-shim-tools/src/lib.rs, td-shim-tools/src/linker.rs, td-shim/src/lib.rs
=> Fix out of bounds in td-shim/src/lib.rs

td-loader/fuzz/fuzz_targets/fuzzlib.rs, td-loader/src/elf.rs, td-loader/src/elf64.rs, td-loader/src/pe.rs
=> td-loader: Fix potential arithmetic overflow and index out of range warnings

td-shim/src/acpi.rs, td-shim/src/event_log.rs
=> td-shim: Fix potantial arithmetic overflow warning

td-layout/src/metadata.rs
=> td-layout: Fix potential arithmetic overflow

devtools/td-layout-config/config.json, td-layout/src/memslice.rs, td-layout/src/runtime.rs, td-shim/src/bin/td-shim/main.rs
Fix the https://github.com/confidential-containers/td-shim/issues/339
=> Measure and extend kernel binary and parameter

td-layout/src/metadata.rs, td-shim-tools/src/loader.rs
=> td-layout: Refactor funtion is_valid_sections()

.github/workflows/main.yml
Correct the traget for PE format payload build
=> Fix CI build issues

td-loader/src/elf64.rs, td-loader/src/pe.rs
=> td-loader: Add unit test case for PR 410

.github/workflows/integration-tdx.yml
Cover 14+ vcpus scenario to validate issue #159
=> Add one test case in CI

td-paging/src/frame.rs
Fix: https://github.com/confidential-containers/td-shim/issues/402
=> td-paging: fix the potential panic inside

td-shim-tools/src/enroller.rs
Fix https://github.com/confidential-containers/td-shim/issues/431
PI spec says FFS files begin with a header that is aligned on an 8-byte boundry. The previous practice was to change all file sizes to 8-byte alignment which resulted in the file not being its real size. This patch writes the real size into the `size` field of `FfsFileHeader` and adds padding zeros at the end of the file.
=> td-shim-tools: correct the firmware file size alignment

.github/workflows/integration-tdx.yml, .github/workflows/integration.yml, .github/workflows/main.yml, README.md
=> Add badges of CI tasks in README.md

.github/workflows/deny.yml, .github/workflows/main.yml, Makefile
1. Add crate td-loader and cc-measurement in lib crate list
2. Define afl-test and libfuzzer-test in Makefile
3. Enable advisories scan in deny.yml
=> Update CI tasks to contain more tests

devtools/td-benchmark/Cargo.toml, devtools/td-benchmark/src/lib.rs, devtools/test-runner-client/Cargo.toml, devtools/test-runner-client/src/lib.rs, td-payload/Cargo.toml, td-payload/src/main.rs, td-shim/Cargo.toml, td-shim/src/bin/td-shim/heap.rs, tests/test-td-payload/Cargo.toml, tests/test-td-payload/src/main.rs
Fix https://github.com/confidential-containers/td-shim/issues/441
=> bump crate `linked_list_allocator` to latest version

td-loader/src/elf64.rs
=> Fix add overflow issue in elf64.rs

sh_script/fuzzing.sh, sh_script/integration_tdx.sh, sh_script/integration_tdx_15.sh
=> Adjust tdx integration test script

td-loader/fuzz/fuzz_targets/fuzzlib.rs, td-loader/src/elf.rs
=> td-loader: Fix potential panic issue

.github/workflows/format.yml, .github/workflows/main.yml, Cargo.toml, README.md, sh_script/build_final.sh
Fix: https://github.com/confidential-containers/td-shim/issues/429
=> Add size optimization and lto for debug build

.github/workflows/fuzz.yml, .github/workflows/main.yml, README.md
1. Add debug build in main.yml
2. Move fuzzing test from main.yml to fuzz.yml
=> Adjust CI tasks

README.md
This reverts commit ce69bfc58c9af88b85b03974efaba14a8009a463 which is pushed by mistake.
=> Revert "readme: fix build instructions"

doc/test_heap_stack_usage.md
=> Docs: Add doc for stack and heap usage.

td-shim/src/bin/td-shim/linux/boot.rs, td-shim/src/bin/td-shim/linux/kernel_param.rs
Fix: https://github.com/confidential-containers/td-shim/issues/465
=> td-shim: add const definitions for Linux setup header

cc-measurement/src/log.rs, td-shim/src/bin/td-shim/td/tdx.rs
Fix: https://github.com/confidential-containers/td-shim/issues/467
=> td-shim: handle errors in extend_rtmr()

tdx-tdcall/src/lib.rs
Signed-off-by: Yang Longlong <longlong.yang@intel.com>
=> tdx-tdcall: change the level of visibility to pub.

td-payload/src/arch/x86_64/cet.rs, td-payload/src/arch/x86_64/init.rs
Fix: https://github.com/confidential-containers/td-shim/issues/508
=> td-payload: set CET.CR4 only if shstk or ibt is available

td-shim/src/acpi.rs, td-shim/src/bin/td-shim/acpi.rs
Fix: https://github.com/confidential-containers/td-shim/issues/454
=> td-shim: handle errors in acpi

tdx-tdcall/src/tdreport.rs
Fix: #541
Add Copy trait for TdInfo TeeTcbInfo ReportMac and ReportType
=> tdx-tdcall: Fix mirai scan issues

cc-measurement/src/log.rs, td-paging/src/page_table.rs, td-payload/src/arch/x86_64/idt.rs, td-payload/src/arch/x86_64/paging.rs
=> Fix warnings reports by MIRAI

.github/workflows/main.yml, td-shim-tools/Cargo.toml
Fix: https://github.com/confidential-containers/td-shim/issues/539
=> Add td-payload-reference-calculator into CI

td-shim/src/metadata.rs
According to `doc/tdshim_spec.md`, `PAGE.AUG` needs to be set for `PermMem` metadata section.
Fix: https://github.com/confidential-containers/td-shim/issues/579
=> td-shim: check `PAGE.AUG` attribute of `PermMem` section

tests/test-td-payload/config/test_config_1.json, tests/test-td-payload/config/test_config_2.json, tests/test-td-payload/config/test_config_3.json, tests/test-td-payload/config/test_config_4.json, tests/test-td-payload/config/test_config_5.json, tests/test-td-payload/src/main.rs, tests/test-td-payload/src/testtdinfo.rs, tests/test-td-payload/src/testtrustedboot.rs
tdinfo: gpaw value can only be 48 or 52
trustedboot: update log format
=> Update test cases

sh_script/fuzzing.sh
=> Fix random fail issue of CI fuzzing test

td-shim/src/metadata.rs
=> add memory address/size check for TD_INFO.

td-payload/src/bin/example/main.rs, td-payload/src/bin/example/stack.rs
=> Fix clippy errors

.github/workflows/format.yml
=> Enhance cargo clippy test in CI

Cargo.lock, td-shim/Cargo.toml
=> Upgrade rustix version to v0.38.30

td-shim-tools/src/tee_info_hash.rs
=> Get metadata buffer size from TDVF DESCRIPTOR

sh_script/fuzzing.sh
=> Fuzzing: Enhance test scripts to detect issue #667

td-shim-interface/README.md
=> Fix td-shim-interface dead link

td-shim-interface/Cargo.toml
Fix: #689 
A patch release from 0.1.0 to 0.1.1
=> Update td-shim-interface version to 0.1.1

td-shim-tools/src/tee_info_hash.rs
=> Should panic when sec.memory_data_size < sec.raw_data_size

td-shim/src/secure_boot.rs
Use a large enough array to hold the formated public key.
Related issue: https://github.com/confidential-containers/td-shim/issues/685
=> td-shim: remove vector in `secure_boot`

doc/test_with_td_payload.md, tests/test-td-payload/config/test_config_1.json, tests/test-td-payload/config/test_config_2.json, tests/test-td-payload/config/test_config_3.json, tests/test-td-payload/config/test_config_4.json, tests/test-td-payload/config/test_config_5.json, tests/test-td-payload/src/testtdinfo.rs
=> Fix test payload build fail

.github/workflows/deny.yml
=> Change schedule of cargo-deny to daily run

.github/workflows/trivy.yml
=> Enable trivy scan in CI

td-exception/src/interrupt.rs
When an exception occurs within the interrupt handler, it will re-enter the `generic_interrupt_handler` function. At this point, the `CALLBACK_TABLE` is in a locked state, which can cause the program to fall into a deadlock.
=> td-exception: release the lock before calling the callback

.github/workflows/deny.yml, .github/workflows/devtools.yml, .github/workflows/format.yml, .github/workflows/fuzz.yml, .github/workflows/integration.yml, .github/workflows/library.yml, .github/workflows/main.yml, .github/workflows/release.yaml, .github/workflows/trivy.yml, doc/cargo-deny.md
=> Upgrade ubuntu version for CI

.github/workflows/devtools.yml, .github/workflows/library.yml, .github/workflows/main.yml
windows-2019 has been deprecated. Upgrade to windows-2022.
=> CI: Upgrade windows version
